version: '{build}'
image: Visual Studio 2022

configuration: Release
platform: x64

install:
  # Install .NET 7 SDK
  - ps: choco install dotnet-7.0-sdk -y

build_script:
  # Restore NuGet packages
  - cmd: nuget restore IceBloc.sln

  # Build the EXE projects explicitly
  - cmd: msbuild IceBloc\IceBloc.csproj /p:Configuration=Release /m
  - cmd: msbuild IceBlocCLI\IceBlocCLI.csproj /p:Configuration=Release /m

artifacts:
  # Collect IceBloc main exe
  - path: 'IceBloc\bin\Release\net7.0-windows\**'
    name: IceBloc-Release

  # Collect IceBloc CLI exe
  - path: 'IceBlocCLI\bin\Release\net7.0\**'
    name: IceBlocCLI-Release
