version: '{build}'
image: Visual Studio 2022

configuration: Release
platform: x64

install:
  # Install .NET 7 SDK
  - ps: choco install dotnet-7.0-sdk -y

build_script:
  # Restore NuGet packages
  - cmd: nuget restore IceBloc.sln

  # Build the solution in Release mode
  - cmd: msbuild IceBloc.sln /p:Configuration=Release /p:Platform=x64 /m

artifacts:
  # IceBloc main exe, DLLs, and runtime files
  - path: 'IceBloc\bin\x64\Release\net7.0-windows\**\*.exe'
    name: IceBloc-Release
  - path: 'IceBloc\bin\x64\Release\net7.0-windows\**\*.dll'
    name: IceBloc-Release
  - path: 'IceBloc\bin\x64\Release\net7.0-windows\**\*.json'
    name: IceBloc-Release

  # IceBlocCLI exe, DLLs, and runtime files
  - path: 'IceBlocCLI\bin\x64\Release\net7.0\**\*.exe'
    name: IceBlocCLI-Release
  - path: 'IceBlocCLI\bin\x64\Release\net7.0\**\*.dll'
    name: IceBlocCLI-Release
  - path: 'IceBlocCLI\bin\x64\Release\net7.0\**\*.json'
    name: IceBlocCLI-Release
