version: '{build}'
image: Visual Studio 2022

configuration: Release
platform: x64

install:
  - ps: choco install dotnet-7.0-sdk -y

build_script:
  # Restore NuGet packages
  - cmd: nuget restore IceBloc.sln

  # Build the solution in Release mode
  - cmd: msbuild IceBloc.sln /p:Configuration=Release /m

artifacts:
  - path: '**\bin\Release\**'
    name: IceBloc-Release

