version: '{build}'
image: Visual Studio 2022

configuration: Release
platform: x64

install:
  # Install .NET 7 SDK
  - ps: choco install dotnet-7.0-sdk -y

build_script:
  # Restore NuGet packages
  - cmd: nuget restore IceBloc.sln

  # Build the solution in Release mode
  - cmd: msbuild IceBloc.sln /p:Configuration=Release /m

  # DEBUG: List all files in the build output folders to find actual output
  - cmd: dir /s /b IceBloc\bin
  - cmd: dir /s /b IceBlocCLI\bin

artifacts:
  # Collect IceBloc main exe / DLL (we’ll fix paths after seeing debug output)
  - path: 'IceBloc\bin\Release\net7.0-windows\**'
    name: IceBloc-Release

  # Collect IceBloc CLI exe / DLL
  - path: 'IceBlocCLI\bin\Release\net7.0\**'
    name: IceBlocCLI-Release
