version: '{build}'
image: Visual Studio 2022

configuration: Release
platform: x64

install:
  # Install .NET 7 SDK
  - ps: choco install dotnet-7.0-sdk -y

build_script:
  # Restore NuGet packages
  - cmd: nuget restore IceBloc.sln

  # Build IceBloc and IceBlocCLI in Release mode as self-contained
  - cmd: msbuild IceBloc.sln /p:Configuration=Release /p:Platform=x64 /p:PublishSingleFile=false /p:RuntimeIdentifier=win-x64 /p:SelfContained=true /m

artifacts:
  # Collect everything from IceBloc output folder
  - path: 'IceBloc\bin\x64\Release\net7.0-windows\**\*'
    name: IceBloc-Full

  # Collect everything from IceBlocCLI output folder
  - path: 'IceBlocCLI\bin\x64\Release\net7.0\**\*'
    name: IceBlocCLI-Full
