# AppVeyor configuration for IceBloc

version: '{build}'
image: Visual Studio 2022

configuration: Release
platform: x64

install:
  # Install .NET 7 SDK
  - ps: choco install dotnet-7.0-sdk -y

build_script:
  # Restore NuGet packages
  - cmd: nuget restore IceBloc.sln

  # Build the solution in Release mode
  - cmd: msbuild IceBloc.sln /p:Configuration=Release /m

artifacts:
  # Collect IceBloc main EXE
  - path: 'IceBloc\bin\Release\net7.0-windows\**\*.exe'
    name: IceBloc-Release

  # Collect IceBloc CLI EXE
  - path: 'IceBlocCLI\bin\Release\net7.0\**\*.exe'
    name: IceBlocCLI-Release

  # Optional: include DLL dependencies if needed
  - path: 'IceBloc\bin\Release\net7.0-windows\**\*.dll'
    name: IceBloc-Dependencies
  - path: 'IceBlocCLI\bin\Release\net7.0\**\*.dll'
    name: IceBlocCLI-Dependencies
